import Head from 'next/head'
import { useEffect, useState } from 'react'
import About from '../components/About'
import Card from '../components/Card'
import ContactMe from '../components/ContactMe'
import Footer from '../components/Footer'
import Skills from '../components/Skills'
import AOS from 'aos';
import 'aos/dist/aos.css'
import {BsFillSunFill, BsFillMoonFill} from  'react-icons/bs'


export default function Home() {
  const [dark, setDark] = useState(false);
  useEffect(() => {
    AOS.init({
      once: false,
    })
  })
  return (
    <div className={` ${dark ? "bg-slate-900" : "bg-gradient-to-r from-indigo-400 via-purple-400 to-pink-400 " }`}>
      <Head>
        <title>Zaid's Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link  rel="icon" href="https://res.cloudinary.com/dqmlanbbj/image/upload/v1640190776/Avatar/ZAIDOP_wtii2t.jpg" />
      </Head>
      <header className="bg-white backdrop-filter backdrop-blur-xl bg-opacity-30 border-b-2 border-gray-400 w-full h-12 top-0 sticky flex items-center justify-between">
      <div className="ml-5 xl:ml-52">
        <img className = "w-9 h-9  rounded-full shadow-xl drop-shadow-sm"src = "https://i.pinimg.com/564x/de/52/b7/de52b7bd3fbd77d5ca765bb6c40b3eb0.jpg" alt=""/>
        </div>
        <div className="mr-5 xl:mr-52 cursor-pointer " >
          {dark === true ? (
            <div className="flex items-center justify-center w-9 h-9 rounded-full hover:bg-yellow-100" onClick={() => setDark(false)}>
              <BsFillSunFill className="text-yellow-500"/>
            </div>
          ) : (
            <div className="flex items-center justify-center w-9 h-9 rounded-full hover:bg-black" onClick={() => setDark(true)}>
              <BsFillMoonFill className="text-white"/>
            </div>
          )}
        </div>
      </header>
      <div className="min-h-screen py-10 px-3 sm:px-5">
      <div data-aos="fade-down" data-aos-duration="800">
      <Card />
      </div>
      <div data-aos="fade-up" data-aos-duration="800" data-aos-delay="400">
      <About/>
      </div>
        <Skills/>
        <ContactMe/>
        <Footer/>
      </div>
    </div>
  )
}
